Repository SOEN6431Winter2025/FitoTrackW25, pull requests merged in 2025-03, with the labels that each got.

#18 Case Study #1: Merge from Group 2
  app/src/main/java/de/tadris/fitness/Instance.java
  app/src/main/java/de/tadris/fitness/activity/EnterWorkoutActivity.java
  app/src/main/java/de/tadris/fitness/activity/ListWorkoutsActivity.java
  app/src/main/java/de/tadris/fitness/activity/WorkoutActivity.java
  app/src/main/java/de/tadris/fitness/recording/PressureService.java
  app/src/main/java/de/tadris/fitness/recording/WorkoutRecorder.java
Labels: Techinical Debt, Group 2

#22 Group_3_Case_Study_1
  app/src/main/java/de/tadris/fitness/activity/EnterWorkoutActivity.java
  app/src/main/java/de/tadris/fitness/activity/FitoTrackActivity.java
  app/src/main/java/de/tadris/fitness/activity/RecordWorkoutActivity.java
  app/src/main/java/de/tadris/fitness/activity/SettingsActivity.java
  app/src/main/java/de/tadris/fitness/activity/ShowWorkoutActivity.java
  app/src/main/java/de/tadris/fitness/util/FileUtils.java
Labels: Techinical Debt, Group_3

#42 Group_3_Case_Study_2
  app/src/main/java/de/tadris/fitness/activity/FitoTrackSettingsActivity.java
  app/src/main/java/de/tadris/fitness/activity/SettingsActivity.java
  app/src/main/java/de/tadris/fitness/activity/UtilsForNumber.java
  app/src/main/java/de/tadris/fitness/activity/VoiceAnnouncementsSettingsActivity.java
  app/src/main/java/de/tadris/fitness/map/tilesource/FitoTrackTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/HumanitarianTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/MapnikTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/ThunderforestTileSource.java
Labels: Group_3, Remove Software Clone

#46 Case Study #2: Merge from Group 2
  app/src/main/java/de/tadris/fitness/activity/FitoTrackActivity.java
  app/src/main/java/de/tadris/fitness/activity/FitoTrackSettingsActivity.java
  app/src/main/java/de/tadris/fitness/activity/MenuUtils.java
  app/src/main/java/de/tadris/fitness/activity/SettingsActivity.java
  app/src/main/java/de/tadris/fitness/activity/WorkoutActivity.java
  app/src/main/java/de/tadris/fitness/map/tilesource/FitoTrackTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/HumanitarianTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/MapnikTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/ThunderforestTileSource.java
  app/src/main/java/de/tadris/fitness/map/tilesource/TileConstantManager.java
  app/src/main/java/de/tadris/fitness/util/DialogUtils.java
Labels: Group 2

#58 Group_3_Case_Study_3
  .gitignore
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/de/tadris/fitness/activity/EnterWorkoutActivity.java
  app/src/main/java/de/tadris/fitness/activity/RecordWorkoutActivity.java
  app/src/main/java/de/tadris/fitness/osm/OAuthUrlProvider.java
Labels: Group_3, Remove Software Vulnerabilities
